### ISSUE TITLE
HTTP ERROR: 404 Problem accessing /webide/index.html. Reason: ProxyServlet: /webide/index.html

### ISSUE THREAD

**Issue by rcv911** [maenujem/webidetest#1]
Hi, I'm trying run ./orion and I got this message on http://localhost:8080/webide/index.html

**Comment by maenujem** [comment]
This could have multiple reasons, as Java and Eclipse and Orion and Browser must fit together..
Did you get any error message in the console when starting orion / calling the website?
What versions of Java/Openjdk and Webide are you using?

**Comment by rcv911** [comment]
- Ubuntu 18.04.4 LTS

- Java version:

````
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
````

- WebIDE

````
sap-webide-personal-edition-1.53.9-trial
````

I did all steps you describe in README.md. Yeah, I've got some errors
````
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.storage.FrameworkExtensionInstaller (file:/home/user/SAP_HANA_WEBIDE/sap-webide-personal-edition-1.53.9-trial-win32.win32.x86_64/eclipse/plugins/org.eclipse.osgi_3.10.2.v20150203-1939.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.storage.FrameworkExtensionInstaller
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
!SESSION 2020-08-20 09:34:09.202 -----------------------------------------------
eclipse.buildId=@qualifier@
java.version=11.0.8
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ru_RU
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -console -data serverworkspace

!ENTRY com.sap.webide.orionplugin 4 0 2020-08-20 09:34:09.860
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.sap.webide.orionplugin [12]
  Unresolved requirement: Require-Bundle: com.sap.webide.orionplugin.reverseproxy
    -> Bundle-SymbolicName: com.sap.webide.orionplugin.reverseproxy; bundle-version="1.53.9"; singleton:="true"
       com.sap.webide.orionplugin.reverseproxy [13]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY com.sap.webide.orionplugin.reverseproxy 4 0 2020-08-20 09:34:09.863
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.sap.webide.orionplugin.reverseproxy [13]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
09:34:10,203 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:34:10,203 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:34:10,203 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [bundleresource://2.fwk707161353:1/logback.xml]
09:34:10,211 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1060147a - URL [bundleresource://2.fwk707161353:1/logback.xml] is not of type file
09:34:10,230 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:34:10,231 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
09:34:10,292 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@33d14a35 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
09:34:10,292 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
09:34:10,292 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:34:10,294 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:34:10,334 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
09:34:10,334 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
09:34:10,334 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
09:34:10,334 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.orion.internal.server.search.Indexer] to INFO
09:34:10,334 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@33d14a35 - Propagating INFO level on Logger[org.eclipse.orion.internal.server.search.Indexer] onto the JUL framework
09:34:10,336 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.orion.server.login] to INFO
09:34:10,336 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@33d14a35 - Propagating INFO level on Logger[org.eclipse.orion.server.login] onto the JUL framework
09:34:10,336 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.orion.server.account] to INFO
09:34:10,336 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@33d14a35 - Propagating INFO level on Logger[org.eclipse.orion.server.account] onto the JUL framework
09:34:10,336 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.orion.server.config] to INFO
09:34:10,336 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@33d14a35 - Propagating INFO level on Logger[org.eclipse.orion.server.config] onto the JUL framework
09:34:10,337 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
09:34:10,337 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@33d14a35 - Propagating WARN level on Logger[ROOT] onto the JUL framework
09:34:10,337 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:34:10,337 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:34:10,338 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@20a9bb90 - Registering current configuration as safe fallback point

2020-08-20 09:34:10.349 [Component Resolve Thread (Bundle 47)] INFO  org.eclipse.orion.server.config - No server configuration file found at: /home/user/SAP_HANA_WEBIDE/sap-webide-personal-edition-1.53.9-trial-win32.win32.x86_64/eclipse/orion.conf
2020-08-20 09:34:10.350 [Component Resolve Thread (Bundle 47)] INFO  org.eclipse.orion.server.config - No server configuration file found at: /home/user/SAP_HANA_WEBIDE/sap-webide-personal-edition-1.53.9-trial-win32.win32.x86_64/eclipse/serverworkspace/orion.conf
2020-08-20 09:34:10.368 [Component Resolve Thread (Bundle 47)] INFO  org.eclipse.orion.server.config - Loaded simple metadata store (version 8).
2020-08-20 09:34:10.375 [Component Resolve Thread (Bundle 47)] WARN  org.eclipse.orion.server.config - No MQTT message broker specified in the orion.conf with orion.events.uri
````

**Comment by maenujem** [comment]
As the version of orion required is quite old, I'm using it with JDK 8, not JDK 11 - so you might want to try this..

**Comment by rcv911** [comment]
Yeah, it works with JDK8. Thank you

**Comment by maenujem** [comment]
Thanks for the positive feedback :)

**Comment by rxdash** [comment]
> As the version of orion required is quite old, I'm using it with JDK 8, not JDK 11 - so you might want to try this..

This worked for me. I tried  JDK/SDK 11, 15, even a different laptop.Thank you so much!
